sudo: false

language: node_js
node_js:
  - 8
  - 7

install:
  - npm install
  - npm install --global coveralls@^2.0.0

script:
  - npm run lint
  - npm run coverage

after_success:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "8" ]; then cat ./coverage/lcov.info | coveralls ; fi'